# Generated by Django 3.1.3 on 2021-08-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_myplan_tribdetail_triplist_usercharacter_visitpos'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
