# Generated by Django 3.1.3 on 2021-08-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210809_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='triplist',
            name='rep_img',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
