# Generated by Django 3.1.3 on 2021-08-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_triplist_rep_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='p_num',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
