# Generated by Django 3.1.3 on 2021-08-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210809_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='triplist',
            name='subtitle',
            field=models.CharField(default='부제', max_length=30),
        ),
        migrations.AlterField(
            model_name='triplist',
            name='rep_img',
            field=models.ImageField(default='default.png', upload_to='accounts/'),
        ),
    ]
